LibXMTPRust.xcframework/Info.plist
LibXMTPRust.xcframework/ios-arm64/Headers/xmtpv3FFI.h
LibXMTPRust.xcframework/ios-arm64_x86_64-simulator/Headers/xmtpv3FFI.h
LibXMTPRust.xcframework/macos-arm64_x86_64/Headers/xmtpv3FFI.h
Sources/LibXMTP/xmtpv3.swift

Was needed to finish https://github.com/xmtp/xmtp-ios/pull/217.

add publish and pagination

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/xmtpv3.swift

I wasn't quite sure if this is the right way to bump this package but I wanted to check to see if I could start pointing https://github.com/xmtp/xmtp-ios/pull/229 at it.

Bump to libxmtp 9126afd

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/xmtpv3.swift

We need the latest for versioning and client creation fixes

Update to latest 

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/xmtpv3.swift

Update the latest that fix the transport issue.

Publish new libxmtp bindings

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/xmtpv3.swift

This bumps to the latest libxmtp to get the group admin work.

Group Admin LibXMTP Bump

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

Updates bindings for streaming groups created after stream start

Updated to libxmtp 8587efd

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

Bump to latest Rust version for listing V2 fix.

Bump rust for list fix

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

Bumps to latest Rust for fix to V2 streaming

Fix streaming dev bug

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

Bump the pod for latest streaming fix

Bump the pod streaming fix

---

.github/CODEOWNERS
LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This bumps to the latest rust package to support decoding push notifications.

Bump to latest rust for Push Notification work

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

Hopefully fix iOS transport errors at the very least better erroring

Transport fix bump

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Delivery status

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Bump rust for latest canMessage changes.

Can Message Hash Map

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This bumps to latest libxmtp to get the newest db functions
Part of https://github.com/xmtp/xmtp-ios/issues/336

Bump for SQL DB Functions

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Fix create bundle

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Get the local db fetch methods and stream improvements.

Bump the bindings

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Bump the version to update optimistic sending.

Bump the libxmtp version

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

See https://github.com/xmtp/libxmtp/pull/918

Custom permissions on group create

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

Fixes intent publishing error and potential for appearance of split groups.

Fix intent publishing

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Bump to latest uniffi

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

libxmtp epoch and members fixes

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

Includes more fixes to prevent forks

More fork fixes

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Bump to a version with more pool connections

iOS performance

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Revoke installations, sync all groups, and better reuse of connections.

Performance improvements and revokation

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Possible group fork fixes, sync all group improvements

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

Skip duplicate message processing by @neekolas https://github.com/xmtp/libxmtp/pull/1022

Bump library again: Skip duplicate message processing

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

Incorporates upstream change https://github.com/xmtp/libxmtp/pull/1041 which includes some streaming performance gains

Stream improvements from upstream libxmtp

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

V3 dms stage zero

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Bump to latest version with group key rotation

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Latest libxmtp

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This improves SCW and improves message listing performance.

Fix SCW and get better message perf

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This gets bindings for consent sync and filtering

Consent sync + consent filtering

---

.github/workflows/deploy_to_cocoapods.yml
.github/workflows/lint.yml
LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Get the latest bindings with consent sync

Consent sync

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

consent syncing fixes
potential fork group fixes
removing first message from dms

Bump the pod version

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Fix TLS issues, consent syncing, and installation signatures

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

Small bump to get performance back

Bump for performance

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Also adds signature verification methods

Bump for consent streaming

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Fixes https://github.com/xmtp/xmtp-ios/issues/436

Link SQL Cipher Directly

---

LibXMTP.podspec
Package.swift

I think this needs to happen one level higher

Revert the sql cipher

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

Make sync all actually sync all.

Bump to a version that syncs all

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Add ability to filter and sync by multiple consents
And new inboxId methods for performance
Last readable message

Update swift bindings for consent filtering

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Messages with reactions, find or create dm, dm fix

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

libxmtp ae4eb9c for db lock fix and remove pinned frame url

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

pod spec lint LibXMTP.podspec 
-> LibXMTP (3.0.23)
...

b137466 libxmtp for stream welcome fix

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Bump the package

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Fix Key Package errors and updates to disappearing messages.

Fix Key Package Errors

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

fix invalid key packages breaking groups.

Fix invalid key packages
