LibXMTP.podspec
Package.swift

`pod spec lint` was failing because the bindings were missing some architecture types. This was fixed here: https://github.com/xmtp/libxmtp/pull/465
This change can be verified by running `pod spec lint LibXMTP.podspec` in the root folder + branch of this PR

Update bindings to includes all archs

---

LibXMTP.podspec
Package.swift
README.md
Sources/LibXMTP/xmtpv3.swift

See new README instructions for updating Swift Package and Cocoapod:
https://github.com/xmtp/libxmtp-swift/blob/cv/bindings-libxmtp-43bc889/README.md

Update to libxmtp  bindings release 43bc889

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Adds the following new functions for xmtp-ios for FfiGroup:
func groupName() throws -> String
func updateGroupName(groupName: String) async throws

update rust libxmtp for group name functions

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Related to https://github.com/xmtp/libxmtp/pull/782

updated for admin, super admin lists from libxmtp

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

PR does not update the podspec version because the latest commit on main is not tagged or released to cocoapods yet.

updated for permission level on members struct

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

Notable Updates:
- Default group name is now empty string
- Now correctly clearing pending commits after invalid permission commits

Update libxmtp to for pending commit fix

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

- update permission function
- read permission policy set
- update/read group description
- admins can update new metadata fields without setting policy first

update bindings to libxmtp e4cfade

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Related to https://github.com/xmtp/libxmtp/pull/888

Adding pinned frame metadata field 

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Adds the optimistic send bindings.

Optimistic Sending Bindings

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

* fix musl-tools by @insipx in https://github.com/xmtp/libxmtp/pull/993
* Stop setting new lifetimes by @neekolas in https://github.com/xmtp/libxmtp/pull/964
* Refactor message history sync, add to CLI by @tuddman in https://github.com/xmtp/libxmtp/pull/930
* Generate latest protos, update affected types by @rygine in https://github.com/xmtp/libxmtp/pull/1009
* Fix node bindings release workflow by @rygine in https://github.com/xmtp/libxmtp/pull/1013
* `xmtp_cryptography` wasm32 target by @insipx in https://github.com/xmtp/libxmtp/pull/1012
* Various updates by @rygine in https://github.com/xmtp/libxmtp/pull/1014
* Add libxmtp version to requests by @neekolas in https://github.com/xmtp/libxmtp/pull/1011
* Store or ignore group messages by @neekolas in …

Bump to latest versions of SDK

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Possible db encryption fix and foundational work for v3 consent

Plaintext heads for encryption and V3 consent

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Also adds additional logging for streaming

Expose timestamp on installation and make members async

---

LibXMTP.podspec
Package.swift

```bash
pod spec lint LibXMTP.podspec 
-> LibXMTP (3.0.11)
- NOTE  | xcodebuild:  note: Using codesigning identity override: -
- NOTE  | [iOS] xcodebuild:  note: Building targets in dependency order
- NOTE  | [iOS] xcodebuild:  note: Target dependency graph (3 targets)
- NOTE  | [iOS] xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. (in target 'LibXMTP' from project 'Pods')
- NOTE  | [iOS] xcodebuild:  note: Signing static framework with --generate-pre-encrypt-hashes (in target 'Pods-App' from project 'Pods')
- NOTE  | [iOS] xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. (in target 'App' from project 'App')
- NOTE  | [iOS] xcodebuild:  note: Disabling previews because SWIFT_VERSION is set and …
```

Update libxmtp for fork fixes via intent filter fix

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

Bumps the bindings for conversation list performance

Bindings for Conversation list performance

---

README.md

Update README to remove the manual publish to cocoapod step and point to GH action.

Update README to remove the manual publish to cocoapod step and point to GH action

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This PR updates the Swift bindings to libxmtp version 4.2.0-dev.35ab145. 
Changes:
- Updated LibXMTP.podspec version to 4.2.0-dev.35ab145

Update to libxmtp 4.2.0-dev.35ab145

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This PR updates the Swift bindings to libxmtp version 4.2.0-dev.38cf550. 
Changes:
- Updated LibXMTP.podspec version to 4.2.0-dev.38cf550

Update to libxmtp 4.2.0-dev.38cf550

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This PR updates the Swift bindings to libxmtp version 4.2.0-dev.59df9d1. 
Changes:
- Updated LibXMTP.podspec version to 4.2.0-dev.59df9d1

Update to libxmtp 4.2.0-dev.59df9d1

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

This PR updates the Swift bindings to libxmtp version 4.2.0-dev.4132dcf. 
Changes:
- Updated LibXMTP.podspec version to 4.2.0-dev.4132dcf

Update to libxmtp 4.2.0-dev.4132dcf

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This PR updates the Swift bindings to libxmtp version 4.2.0-dev.d811cc6. 
Changes:
- Updated LibXMTP.podspec version to 4.2.0-dev.d811cc6

Update to libxmtp 4.2.0-dev.d811cc6

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

This PR updates the Swift bindings to libxmtp version 4.2.0-dev.4ba3b55. 
Changes:
- Updated LibXMTP.podspec version to 4.2.0-dev.4ba3b55

Update to libxmtp 4.2.0-dev.4ba3b55

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This PR updates the Swift bindings to libxmtp version 4.1.5. 
Changes:
- Updated LibXMTP.podspec version to 4.1.5

Update to libxmtp 4.0.5

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This PR updates the Swift bindings to libxmtp version 4.2.0-rc1. 
Changes:
- Updated LibXMTP.podspec version to 4.2.0-rc1

Update to libxmtp 4.2.0-rc1

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This PR updates the Swift bindings to libxmtp version 4.2.0-rc2. 
Changes:
- Updated LibXMTP.podspec version to 4.2.0-rc2

Update to libxmtp 4.2.0-rc2

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This PR updates the Swift bindings to libxmtp version 4.2.0-rc4. 
Changes:
- Updated LibXMTP.podspec version to 4.2.0-rc4

Update to libxmtp 4.2.0-rc4

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

This PR updates the Swift bindings to libxmtp version 4.2.0-rc5. 
Changes:
- Updated LibXMTP.podspec version to 4.2.0-rc5

Update to libxmtp 4.2.0-rc5

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This PR updates the Swift bindings to libxmtp version 4.2.2. 
Changes:
- Updated LibXMTP.podspec version to 4.2.2

Update to libxmtp 4.2.2

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This PR updates the Swift bindings to libxmtp version 4.2.3. 
Changes:
- Updated LibXMTP.podspec version to 4.2.3

Update to libxmtp 4.2.3

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

This PR updates the Swift bindings to libxmtp version 4.2.6. 
Changes:
- Updated LibXMTP.podspec version to 4.2.6

Update to libxmtp 4.2.6

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This PR updates the Swift bindings to libxmtp version 4.3.0-dev.d5f91eb. 
Changes:
- Updated LibXMTP.podspec version to 4.3.0-dev.d5f91eb

Update to libxmtp 4.3.0-dev.d5f91eb

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This PR updates the Swift bindings to libxmtp version 4.2.8. 
Changes:
- Updated LibXMTP.podspec version to 4.2.8

Update to libxmtp 4.2.8

---

LibXMTP.podspec
Sources/LibXMTP/xmtpv3.swift

This PR updates the Swift bindings to libxmtp version 4.3.0-rc1. 
Changes:
- Updated LibXMTP.podspec version to 4.3.0-rc1

Update to libxmtp 4.3.0-rc1

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

This PR updates the Swift bindings to libxmtp version 4.3.0-rc2. 
Changes:
- Updated LibXMTP.podspec version to 4.3.0-rc2

Update to libxmtp 4.3.0-rc2

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

This PR updates the Swift bindings to libxmtp version 4.3.0. 
Changes:
- Updated LibXMTP.podspec version to 4.3.0

Update to libxmtp 4.3.0

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

This PR updates the Swift bindings to libxmtp version 4.4.0-dev.7f5d8e0. 
Changes:
- Updated LibXMTP.podspec version to 4.4.0-dev.7f5d8e0

Update to libxmtp 4.4.0-dev.7f5d8e0

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt

This PR updates the Swift bindings to libxmtp version 4.3.5. 
Changes:
- Updated LibXMTP.podspec version to 4.3.5

Update to libxmtp 4.3.5

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This PR updates the Swift bindings to libxmtp version 4.4.0-rc1. 
Changes:
- Updated LibXMTP.podspec version to 4.4.0-rc1

Update to libxmtp 4.4.0-rc1

---

LibXMTP.podspec
Package.swift
Sources/LibXMTP/libxmtp-version.txt
Sources/LibXMTP/xmtpv3.swift

This PR updates the Swift bindings to libxmtp version 4.3.7. 
Changes:
- Updated LibXMTP.podspec version to 4.3.7

Update to libxmtp 4.3.7
